### ISSUE TITLE
Duplicate tasks in JIRA

### ISSUE THREAD

**Issue by lech1991** [OWASP/glue#157]
**Description**
Tasks are created in the JIRA system, but the filter that eliminates duplication does not work. Duplicates are created because the jql query is incorrect and incorrectly verified by the "fingerprint".

**Proposed solution**
I found a working solution.
https://community.atlassian.com/t5/Jira-questions/CONTAINS-does-not-seem-to-work-when-searching-description/qaq-p/408602
I tested this solution on local machine and it's working.

**Comment by lech1991** [comment]
The problem is the wrong symbol "_" in the fingerprints.
The CONTAINS (~) operator incorrectly supports fingerprint.

Maybe, remove the "_" symbol from the fingeprint (by changing the jq instruction
"fingerprint": "\ ($ in.pluginid) _ \ ($ h.uri) _ \ ($ h.method)" on
"fingerprint": "\ ($ in.pluginid) \ ($ h.uri) \ ($ h.method)"

@omerlh What do you think about such an idea?

**Comment by omerlh** [comment]
Sounds good! Seems like no need for a PR, right?

**Comment by lech1991** [comment]
@omerlh Unfortunately, the solution does not work. The jql filter is incorrect. 
I made the test.

Actual jql query 
![zrzut1](https://user-images.githubusercontent.com/16288997/55799826-97ec7980-5ad2-11e9-9982-66e73302b986.png)

Modify jql query (based on https://community.atlassian.com/t5/Jira-questions/CONTAINS-does-not-seem-to-work-when-searching-description/qaq-p/408602)
Below is an example output :
![zrzut2](https://user-images.githubusercontent.com/16288997/55800046-0fbaa400-5ad3-11e9-8d48-d6c6e17f2613.png)

in the file glue / lib / glue / filters / jira_one_time_filter.rb (line 46)

**Comment by omerlh** [comment]
Will you able to contribute this PR?

**Comment by lech1991** [comment]
I will try :-), but I will need help with modification
/glue/lib/glue/filters/jira_one_time_filter.rb:46.

**I changed**
`jira.Issue.jql ("project = # {@ project} AND description ~ '# {finding.fingerprint}' AND resolution is EMPTY '). each to | issue |`

**on**
`jira.Issue.jql ("project = # {@ project} AND description ~ **' "\"#{finding.fingerprint}\"" '** AND resolution is EMPTY"). each to | issue |`

I tried this way, but I get the error:
```
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:117:in `require': /glue/lib/glue/filters/jira_one_time_filter.rb:46: syntax error, unexpected $undefined, expecting ')' (SyntaxError)
project} AND description ~ '"\"#{finding.fingerprint}\""' AN
                              ^
/glue/lib/glue/filters/jira_one_time_filter.rb:46: unterminated string meets end of file
/glue/lib/glue/filters/jira_one_time_filter.rb:46: syntax error, unexpected end-of-input, expecting keyword_end
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:117:in `require'
	from /glue/lib/glue/filters.rb:40:in `block in <top (required)>'
	from /glue/lib/glue/filters.rb:39:in `each'
	from /glue/lib/glue/filters.rb:39:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /glue/lib/glue.rb:248:in `scan'
	from /glue/lib/glue.rb:47:in `run'
	from bin/glue:58:in `<main>'

```

**Comment by omerlh** [comment]
Let's move to OWASP slack, it will be faster - feel free to ping me there :)
