### ISSUE TITLE
Getting Segmentation fault error

### ISSUE THREAD

**Issue by KMadhuSudhan** [OWASP/glue#42]
owasp-pipeline-0.8.7/lib/pipeline/util.rb:13: [BUG] Segmentation fault at 0x00000000000000
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0003 p:---- s:0008 e:000007 CFUNC  :gets
c:0002 p:0036 s:0005 e:000004 BLOCK  /usr/local/rvm/gems/ruby-2.3.0/gems/owasp-pipeline-0.8.7/lib/pipeline/util.rb:13 [FINISH]
c:0001 p:---- s:0002 e:000001 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/usr/local/rvm/gems/ruby-2.3.0/gems/owasp-pipeline-0.8.7/lib/pipeline/util.rb:13:in `block (2 levels) in runsystem'
/usr/local/rvm/gems/ruby-2.3.0/gems/owasp-pipeline-0.8.7/lib/pipeline/util.rb:13:in `gets'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f9c8fed6e21 RBP: 0x00000000000000b0 RSP: 0x00007f9c3827ffc0
 RAX: 0x00007f9c3828004f RBX: 0x00007f9c2c000020 RCX: 0x0000000000000007
 RDX: 0x00000000000000b0 RDI: 0x00007f9c2c000020 RSI: 0x00000000000136a0
  R8: 0x0000000000000000  R9: 0x6f6e203a766e652f R10: 0x0000000000000000
 R11: 0x0000000000000206 R12: 0x00007f9c2c47cb00 R13: 0x000000000000000b
 R14: 0x00007f9c2c000078 R15: 0x0000000000002710 EFL: 0x0000000000010283

-- C level backtrace information -------------------------------------------

System configuration:
 ubuntu 14.04, 4 core ,16GB RAM,Ruby 2.3.0,Rails 4.2.5

**Comment by 10dot** [comment]
An upgrade to glue 0.9.2+ (the current master branch);  I added several thread safety fixes that should prevent this.

**Comment by omerlh** [comment]
I'm closing this issue for now, re-open if it reproduce.
